// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostPullRequestCreateWithBody request with any body
	PostPullRequestCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestCreate(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPullRequestMergeWithBody request with any body
	PostPullRequestMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestMerge(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPullRequestReassignWithBody request with any body
	PostPullRequestReassignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPullRequestReassign(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatsReviewers request
	GetStatsReviewers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTeamAddWithBody request with any body
	PostTeamAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTeamAdd(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTeamDeactivateWithBody request with any body
	PostTeamDeactivateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTeamDeactivate(ctx context.Context, body PostTeamDeactivateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTeamGet request
	GetTeamGet(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersGetReview request
	GetUsersGetReview(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUsersSetIsActiveWithBody request with any body
	PostUsersSetIsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostUsersSetIsActive(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostPullRequestCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestCreate(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestMergeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestMerge(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestMergeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestReassignWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestReassignRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPullRequestReassign(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPullRequestReassignRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatsReviewers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatsReviewersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamAddWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamAddRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamAdd(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamAddRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamDeactivateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamDeactivateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTeamDeactivate(ctx context.Context, body PostTeamDeactivateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTeamDeactivateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTeamGet(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTeamGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersGetReview(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersGetReviewRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUsersSetIsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUsersSetIsActiveRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUsersSetIsActive(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUsersSetIsActiveRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostPullRequestCreateRequest calls the generic PostPullRequestCreate builder with application/json body
func NewPostPullRequestCreateRequest(server string, body PostPullRequestCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestCreateRequestWithBody generates requests for PostPullRequestCreate with any type of body
func NewPostPullRequestCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/create")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostPullRequestMergeRequest calls the generic PostPullRequestMerge builder with application/json body
func NewPostPullRequestMergeRequest(server string, body PostPullRequestMergeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestMergeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestMergeRequestWithBody generates requests for PostPullRequestMerge with any type of body
func NewPostPullRequestMergeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/merge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostPullRequestReassignRequest calls the generic PostPullRequestReassign builder with application/json body
func NewPostPullRequestReassignRequest(server string, body PostPullRequestReassignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPullRequestReassignRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPullRequestReassignRequestWithBody generates requests for PostPullRequestReassign with any type of body
func NewPostPullRequestReassignRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pullRequest/reassign")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetStatsReviewersRequest generates requests for GetStatsReviewers
func NewGetStatsReviewersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stats/reviewers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostTeamAddRequest calls the generic PostTeamAdd builder with application/json body
func NewPostTeamAddRequest(server string, body PostTeamAddJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTeamAddRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTeamAddRequestWithBody generates requests for PostTeamAdd with any type of body
func NewPostTeamAddRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/team/add")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTeamDeactivateRequest calls the generic PostTeamDeactivate builder with application/json body
func NewPostTeamDeactivateRequest(server string, body PostTeamDeactivateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTeamDeactivateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTeamDeactivateRequestWithBody generates requests for PostTeamDeactivate with any type of body
func NewPostTeamDeactivateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/team/deactivate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTeamGetRequest generates requests for GetTeamGet
func NewGetTeamGetRequest(server string, params *GetTeamGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/team/get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "team_name", runtime.ParamLocationQuery, params.TeamName); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersGetReviewRequest generates requests for GetUsersGetReview
func NewGetUsersGetReviewRequest(server string, params *GetUsersGetReviewParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/getReview")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostUsersSetIsActiveRequest calls the generic PostUsersSetIsActive builder with application/json body
func NewPostUsersSetIsActiveRequest(server string, body PostUsersSetIsActiveJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUsersSetIsActiveRequestWithBody(server, "application/json", bodyReader)
}

// NewPostUsersSetIsActiveRequestWithBody generates requests for PostUsersSetIsActive with any type of body
func NewPostUsersSetIsActiveRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/setIsActive")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostPullRequestCreateWithBodyWithResponse request with any body
	PostPullRequestCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error)

	PostPullRequestCreateWithResponse(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error)

	// PostPullRequestMergeWithBodyWithResponse request with any body
	PostPullRequestMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error)

	PostPullRequestMergeWithResponse(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error)

	// PostPullRequestReassignWithBodyWithResponse request with any body
	PostPullRequestReassignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error)

	PostPullRequestReassignWithResponse(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error)

	// GetStatsReviewersWithResponse request
	GetStatsReviewersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatsReviewersResponse, error)

	// PostTeamAddWithBodyWithResponse request with any body
	PostTeamAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error)

	PostTeamAddWithResponse(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error)

	// PostTeamDeactivateWithBodyWithResponse request with any body
	PostTeamDeactivateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamDeactivateResponse, error)

	PostTeamDeactivateWithResponse(ctx context.Context, body PostTeamDeactivateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamDeactivateResponse, error)

	// GetTeamGetWithResponse request
	GetTeamGetWithResponse(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*GetTeamGetResponse, error)

	// GetUsersGetReviewWithResponse request
	GetUsersGetReviewWithResponse(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*GetUsersGetReviewResponse, error)

	// PostUsersSetIsActiveWithBodyWithResponse request with any body
	PostUsersSetIsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error)

	PostUsersSetIsActiveWithResponse(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error)
}

type PostPullRequestCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Pr *PullRequest `json:"pr,omitempty"`
	}
	JSON404 *ErrorResponse
	JSON409 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPullRequestMergeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Pr *PullRequest `json:"pr,omitempty"`
	}
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestMergeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestMergeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPullRequestReassignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Pr PullRequest `json:"pr"`

		// ReplacedBy user_id нового ревьювера
		ReplacedBy string `json:"replaced_by"`
	}
	JSON404 *ErrorResponse
	JSON409 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostPullRequestReassignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPullRequestReassignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatsReviewersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReviewerStatsResponse
}

// Status returns HTTPResponse.Status
func (r GetStatsReviewersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatsReviewersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTeamAddResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Team *Team `json:"team,omitempty"`
	}
	JSON400 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTeamAddResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTeamAddResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTeamDeactivateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TeamDeactivateResult
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTeamDeactivateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTeamDeactivateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTeamGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Team
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTeamGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTeamGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersGetReviewResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		PullRequests []PullRequestShort `json:"pull_requests"`
		UserId       string             `json:"user_id"`
	}
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetUsersGetReviewResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersGetReviewResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUsersSetIsActiveResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		User *User `json:"user,omitempty"`
	}
	JSON401 *ErrorResponse
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostUsersSetIsActiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUsersSetIsActiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostPullRequestCreateWithBodyWithResponse request with arbitrary body returning *PostPullRequestCreateResponse
func (c *ClientWithResponses) PostPullRequestCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error) {
	rsp, err := c.PostPullRequestCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestCreateResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestCreateWithResponse(ctx context.Context, body PostPullRequestCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestCreateResponse, error) {
	rsp, err := c.PostPullRequestCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestCreateResponse(rsp)
}

// PostPullRequestMergeWithBodyWithResponse request with arbitrary body returning *PostPullRequestMergeResponse
func (c *ClientWithResponses) PostPullRequestMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error) {
	rsp, err := c.PostPullRequestMergeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestMergeResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestMergeWithResponse(ctx context.Context, body PostPullRequestMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestMergeResponse, error) {
	rsp, err := c.PostPullRequestMerge(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestMergeResponse(rsp)
}

// PostPullRequestReassignWithBodyWithResponse request with arbitrary body returning *PostPullRequestReassignResponse
func (c *ClientWithResponses) PostPullRequestReassignWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error) {
	rsp, err := c.PostPullRequestReassignWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestReassignResponse(rsp)
}

func (c *ClientWithResponses) PostPullRequestReassignWithResponse(ctx context.Context, body PostPullRequestReassignJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPullRequestReassignResponse, error) {
	rsp, err := c.PostPullRequestReassign(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPullRequestReassignResponse(rsp)
}

// GetStatsReviewersWithResponse request returning *GetStatsReviewersResponse
func (c *ClientWithResponses) GetStatsReviewersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatsReviewersResponse, error) {
	rsp, err := c.GetStatsReviewers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatsReviewersResponse(rsp)
}

// PostTeamAddWithBodyWithResponse request with arbitrary body returning *PostTeamAddResponse
func (c *ClientWithResponses) PostTeamAddWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error) {
	rsp, err := c.PostTeamAddWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamAddResponse(rsp)
}

func (c *ClientWithResponses) PostTeamAddWithResponse(ctx context.Context, body PostTeamAddJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamAddResponse, error) {
	rsp, err := c.PostTeamAdd(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamAddResponse(rsp)
}

// PostTeamDeactivateWithBodyWithResponse request with arbitrary body returning *PostTeamDeactivateResponse
func (c *ClientWithResponses) PostTeamDeactivateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTeamDeactivateResponse, error) {
	rsp, err := c.PostTeamDeactivateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamDeactivateResponse(rsp)
}

func (c *ClientWithResponses) PostTeamDeactivateWithResponse(ctx context.Context, body PostTeamDeactivateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTeamDeactivateResponse, error) {
	rsp, err := c.PostTeamDeactivate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTeamDeactivateResponse(rsp)
}

// GetTeamGetWithResponse request returning *GetTeamGetResponse
func (c *ClientWithResponses) GetTeamGetWithResponse(ctx context.Context, params *GetTeamGetParams, reqEditors ...RequestEditorFn) (*GetTeamGetResponse, error) {
	rsp, err := c.GetTeamGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTeamGetResponse(rsp)
}

// GetUsersGetReviewWithResponse request returning *GetUsersGetReviewResponse
func (c *ClientWithResponses) GetUsersGetReviewWithResponse(ctx context.Context, params *GetUsersGetReviewParams, reqEditors ...RequestEditorFn) (*GetUsersGetReviewResponse, error) {
	rsp, err := c.GetUsersGetReview(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersGetReviewResponse(rsp)
}

// PostUsersSetIsActiveWithBodyWithResponse request with arbitrary body returning *PostUsersSetIsActiveResponse
func (c *ClientWithResponses) PostUsersSetIsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error) {
	rsp, err := c.PostUsersSetIsActiveWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUsersSetIsActiveResponse(rsp)
}

func (c *ClientWithResponses) PostUsersSetIsActiveWithResponse(ctx context.Context, body PostUsersSetIsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUsersSetIsActiveResponse, error) {
	rsp, err := c.PostUsersSetIsActive(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUsersSetIsActiveResponse(rsp)
}

// ParsePostPullRequestCreateResponse parses an HTTP response from a PostPullRequestCreateWithResponse call
func ParsePostPullRequestCreateResponse(rsp *http.Response) (*PostPullRequestCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Pr *PullRequest `json:"pr,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParsePostPullRequestMergeResponse parses an HTTP response from a PostPullRequestMergeWithResponse call
func ParsePostPullRequestMergeResponse(rsp *http.Response) (*PostPullRequestMergeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestMergeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Pr *PullRequest `json:"pr,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostPullRequestReassignResponse parses an HTTP response from a PostPullRequestReassignWithResponse call
func ParsePostPullRequestReassignResponse(rsp *http.Response) (*PostPullRequestReassignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPullRequestReassignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Pr PullRequest `json:"pr"`

			// ReplacedBy user_id нового ревьювера
			ReplacedBy string `json:"replaced_by"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetStatsReviewersResponse parses an HTTP response from a GetStatsReviewersWithResponse call
func ParseGetStatsReviewersResponse(rsp *http.Response) (*GetStatsReviewersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatsReviewersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReviewerStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostTeamAddResponse parses an HTTP response from a PostTeamAddWithResponse call
func ParsePostTeamAddResponse(rsp *http.Response) (*PostTeamAddResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTeamAddResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Team *Team `json:"team,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePostTeamDeactivateResponse parses an HTTP response from a PostTeamDeactivateWithResponse call
func ParsePostTeamDeactivateResponse(rsp *http.Response) (*PostTeamDeactivateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTeamDeactivateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TeamDeactivateResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetTeamGetResponse parses an HTTP response from a GetTeamGetWithResponse call
func ParseGetTeamGetResponse(rsp *http.Response) (*GetTeamGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTeamGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetUsersGetReviewResponse parses an HTTP response from a GetUsersGetReviewWithResponse call
func ParseGetUsersGetReviewResponse(rsp *http.Response) (*GetUsersGetReviewResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersGetReviewResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			PullRequests []PullRequestShort `json:"pull_requests"`
			UserId       string             `json:"user_id"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostUsersSetIsActiveResponse parses an HTTP response from a PostUsersSetIsActiveWithResponse call
func ParsePostUsersSetIsActiveResponse(rsp *http.Response) (*PostUsersSetIsActiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUsersSetIsActiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			User *User `json:"user,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
